---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: insecure-ingress
  namespace: authelia
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: app1-tls
    hosts:
    - app1.kube.example.com
  rules:
  - host: app1.kube.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: test-app1-service
          servicePort: 80
  - host: home.kube.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: test-app-home-service
          servicePort: 80
