---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
  labels:
    app: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - name: authelia
        image: clems4ever/authelia:v3.7.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/authelia
      volumes:
      - name: config-volume
        configMap:
          name: authelia-config
          items:
          - key: config.yml
            path: config.yml
